# Generated by Django 5.1.2 on 2024-10-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('nombre', models.CharField(max_length=100)),
                ('fotoPerfil', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('experiencia', models.TextField(blank=True, null=True)),
                ('educacion', models.TextField(blank=True, null=True)),
                ('habilidades', models.TextField(blank=True, null=True)),
                ('certificaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
